name: Release binaries

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:

  generate_ubuntu_x86-64:
    name: Publish artifacts for ubuntu-latest (x86-64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust 1.70.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          override: true
      - name: Build artifacts
        run: cargo build --release --workspace --all-features --verbose
      - name: Upload build artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'target/release/*.so'
