name: Release binaries

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:

  generate_ubuntu_x86-64:
    name: Create artifacts for x86/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build artifacts
        run: cargo build --release --workspace --all-features --verbose
      - name: Upload build artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'target/release/*.so'
